name: Fictional Events
favicon: null
layout_spectrum: 0.55248
typography_spectrum: 0.21238
title: Fiction ?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68951222-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.24282743292860687
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
