name: Fiction ?
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: Fiction ?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68951222-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#6bad3b'
    - '#49631c'
    - '#aa1027'
  brandStrength: 0.5
  lightness: 0.24282743292860687
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
